<?php

//ini_set("display_errors","1");

function display_privacy_policy() {
    echo '<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Privacy Policy - Lumber Spine Rehab App</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                line-height: 1.6;
                margin: 0;
                padding: 0;
                background-color: #f4f4f4;
            }
            .container {
                max-width: 800px;
                margin: 50px auto;
                padding: 20px;
                background: #fff;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            }
            h1, h2, h3 {
                color: #333;
            }
            p {
                color: #555;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Privacy Policy</h1>
            <p>Welcome to Lumber Spine Rehab App, an application designed to assist individuals in managing their spinal health through personalized assessments, exercise recommendations, and health tracking tools. This Privacy Policy explains how we collect, use, and protect your personal data when you use our services.</p>
            
            <h2>Interpretation and Definitions</h2>
            <h3>Interpretation</h3>
            <p>Words with initial letters capitalized have meanings defined below. These definitions will have the same meaning regardless of whether they appear in singular or plural form.</p>
            
            <h3>Definitions</h3>
            <ul>
                <li><strong>Account:</strong> A unique account created for You to access our Service or parts of it.</li>
                <li><strong>Affiliate:</strong> An entity controlling, controlled by, or under common control with a party.</li>
                <li><strong>Application:</strong> Refers to Lumber Spine Rehab App, the software provided by the Company.</li>
                <li><strong>Company:</strong> Refers to Lumber Spine Rehab App.</li>
                <li><strong>Country:</strong> Tamil Nadu, India.</li>
                <li><strong>Device:</strong> Any device capable of accessing the Service, such as a computer, cellphone, or tablet.</li>
                <li><strong>Personal Data:</strong> Any information relating to an identified or identifiable individual.</li>
                <li><strong>Service:</strong> The Application.</li>
                <li><strong>Service Provider:</strong> Any person or entity processing data on behalf of the Company.</li>
                <li><strong>Usage Data:</strong> Data collected automatically, generated by the use of the Service or from the Service infrastructure.</li>
                <li><strong>You:</strong> The individual or entity accessing or using the Service.</li>
            </ul>
            
            <h2>Collecting and Using Your Personal Data</h2>
            <h3>Types of Data Collected</h3>
            
            <h4>Personal Data</h4>
            <p>While using Our Service, We may ask You to provide certain identifiable information that can be used to contact or identify You. Personal information may include, but is not limited to:</p>
            <ul>
                <li>Name</li>
                <li>Register Number</li>
                <li>Email address</li>
                <li>Gender</li>
                <li>Department</li>
                <li>Workplace</li>
                <li>Password</li>
                <li>Phone number</li>
                <li>Photo</li>
                <li>Videos</li>
                <li>Reports</li>
            </ul>
            
            <h4>Usage Data</h4>
            <p>Usage Data is collected automatically when using the Service. It may include information such as Your Device\'s IP address, browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, time spent on those pages, unique device identifiers, and other diagnostic data.</p>
            
            <h2>Sharing Your Personal Data</h2>
            <ul>
                <li><strong>With Service Providers:</strong> To manage and analyze the use of our Service and support spinal health management.</li>
                <li><strong>For Business Transfers:</strong> During mergers, sales, or acquisitions.</li>
                <li><strong>With Affiliates:</strong> Including our parent company and other subsidiaries under common control.</li>
                <li><strong>With Business Partners:</strong> To offer health-related products, services, or promotions related to spinal health management.</li>
                <li><strong>With Other Users:</strong> When interacting publicly or sharing personal information.</li>
                <li><strong>With Your Consent:</strong> For any other purpose with your explicit consent.</li>
            </ul>
            
            <h2>Retention of Your Personal Data</h2>
            <p>We retain Your Personal Data only for as long as necessary to fulfill the purposes outlined in this Privacy Policy, and to comply with legal obligations. Health-related data such as videos, photos, and reports will be retained to track and manage spinal health.</p>
            
            <h2>Security of Your Personal Data</h2>
            <p>We strive to protect your data but cannot guarantee absolute security. We use commercially acceptable methods to safeguard your Personal Data.</p>
            
            <h2>Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, you can contact us at <a href="mailto:nimmakayaladileep647@gmail.com">nimmakayaladileep647@gmail.com</a>.</p>
            
            <p>© 2024 Lumber Spine Rehab App. All rights reserved.</p>
        </div>
    </body>
    </html>';
}

// Call the function to display the privacy policy
display_privacy_policy();
?>
